apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: personhendelse.v1
  namespace: bidrag
  labels:
    team: bidrag
  annotations:
    dcat.data.nav.no/title: "Personhendelser for Bidrag"
    dcat.data.nav.no/description: "Personhendelser av interesser for Bidrag"
    kafka.nais.io/removeDataWhenResourceIsDeleted: "true"

spec:
  pool: nav-prod
  config: # optional; all fields are optional too; defaults shown
    cleanupPolicy: compact  # delete, compact, compact,delete
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3  # see min/max requirements
    retentionBytes: -1
    retentionHours: 800
  acl:
    - team: bidrag
      application: bidrag-person-hendelse
      access: readwrite
    - team: bidrag
      application: bidrag-aktoerregister
      access: read
    - team: bidrag
      application: bidrag-kafka-manager
      access: read
