apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: bidrag-person-hendelse
  namespace: bidrag
  labels:
    team: bidrag

spec:
  image: {{ image }}
  port: 8090
  leaderElection: true
  liveness:
    path: /internal/health
    initialDelay: 50
    failureThreshold: 10
  readiness:
    path: /internal/health
    initialDelay: 50
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 2048Mi
      cpu: "2"
    requests:
      memory: 1024Mi
      cpu: 200m
  ingresses:
    - https://bidrag-person-hendelse.dev.intern.nav.no
    - https://bidrag-person-hendelse.dev.adeo.no
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev, nais
  secureLogs:
    enabled: true
  kafka:
    pool: nav-dev