apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: bidrag-person-hendelse
  namespace: bidrag
  labels:
    team: bidrag

spec:
  image: {{ image }}
  port: 8090
  leaderElection: true
  azure:
    application:
      enabled: true
  liveness:
    path: /internal/health
    initialDelay: 50
    failureThreshold: 10
  readiness:
    path: /internal/health
    initialDelay: 50
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 4Gi
      cpu: "1"
    requests:
      memory: 2Gi
      cpu: 200m
  secureLogs:
    enabled: true
  ingresses: # Optional. List of ingress URLs that will route HTTP traffic to the application.
    - https://bidrag-person-hendelse.intern.nav.no
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod, nais
  kafka:
    pool: nav-prod
