apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: bidrag-person-hendelse
  namespace: bidrag
  labels:
    team: bidrag

spec:
  image: {{ image }}
  port: 8090
  leaderElection: true
  azure:
    application:
      enabled: true
  liveness:
    path: /internal/health
    initialDelay: 90
    failureThreshold: 10
  readiness:
    path: /internal/health
    initialDelay: 90
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 4Gi
      cpu: "1"
    requests:
      memory: 2Gi
      cpu: 200m
  secureLogs:
    enabled: true
  ingresses: # Optional. List of ingress URLs that will route HTTP traffic to the application.
    - https://bidrag-person-hendelse.intern.nav.no
  envFrom:
    - secret: bidrag-person-hendelse-passord-systembruker
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod, i-sky
  kafka:
    pool: nav-prod
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudsql.client
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: person-hendelse-prod
            envVarPrefix: DB
