# WMQ
WMQ_HOST: b27apvl222.preprod.local
WMQ_PORT: 1413
WMQ_CHANNEL: Q2_BID_PERS_HENDELSE
WMQ_QUEUE_MANAGER: MQLS04
WMQ_USERNAME: srvbdpers-hendelse
WMQ_PASSWORD: {MQ_PASSWORD}
WMQ_TIMEOUT: 15000
WMQ_APPLICATION_NAME: bidrag-person-hendelse