# WMQ
WMQ_HOST: a01apvl269.adeo.no
WMQ_PORT: 1414
WMQ_CHANNEL: P_BIDRAG_PERSON_HENDELSE
WMQ_QUEUE_MANAGER: MPLS02
WMQ_USERNAME: srvbidrag-person-hendelse
WMQ_PASSWORD: {MQ_PASSWORD}
WMQ_TIMEOUT: 15000
WMQ_APPLICATION_NAME: bidrag-person-hendelse