# WMQ
WMQ_HOST: mpls04.adeo.no
WMQ_PORT: 1414
WMQ_CHANNEL: P_BID_PERS_HENDELSE
WMQ_QUEUEMANAGER: MPLS04
WMQ_TIMEOUT: 15000
WMQ_APPLICATION_NAME: bidrag-person-hendelse
WMQ_QUEUE_NAME_LIVSHENDELSER: P.BISYS.PDL_LIVSHENDELSER

# Generelt
KJØREPLAN_OVERFØRE_HENDELSER: "0 0/30 * * * ?"
KJØREPLAN_SLETTE_HENDELSER: "0 30 1 * * ?"
DAGER_LEVETID_UTGÅTTE_HENDELSER: 7
