application:
  name: bidrag-person-hendelse

server:
  servlet:
    context-path: /
    encoding.charset: UTF-8
  port: 8090
spring:
  main:
    allow-bean-definition-overriding: true
  autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  main.banner-mode: "off"
  cloud.gcp.sql:
    database-name: ${DB_DATABASE}
    instance-connection-name: ${GCP_TEAM_PROJECT_ID}:europe-north1:${NAIS_APP_NAME}
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}?user=${DB_USERNAME}&password=${DB_PASSWORD}
    hikari:
      idle-timeout: 10001
      max-lifetime: 30001
      connectionTimeout: 30000
      maximum-pool-size: 10
      minimum-idle: 1
  flyway:
    enabled: true
    locations: classpath:/db/migration
  jpa:
    hibernate.connection.provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      jakarta.persistence.sharedCache.mode: UNSPECIFIED
    database: postgresql
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    properties:
      schema.registry.url: ${KAFKA_SCHEMA_REGISTRY}
      basic.auth.credentials.source: USER_INFO
      basic.auth.user.info: ${KAFKA_SCHEMA_REGISTRY_USER}:${KAFKA_SCHEMA_REGISTRY_PASSWORD}
      security:
        protocol: SSL
      ssl:
        keystore:
          type: PKCS12
          location: ${KAFKA_KEYSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
        truststore:
          type: PKCS12
          location: ${KAFKA_TRUSTSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
    producer:
      buffer-memory: 68554432
      retries: 0
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      max-poll-records: 1
      auto-offset-reset: latest
      enable-auto-commit: false
  jackson:
    deserialization:
      # Allerede satt i felles, setter her slik at det gjelder for rest-params også
      FAIL_ON_UNKNOWN_PROPERTIES: false

logging:
  config: "classpath:logback-spring.xml"

retry.backoff.delay: 5000

no.nav.security.jwt:
  dont-propagate-bearertoken: true
  client.registration:
    bidrag-person:
      resource-url: ${BIDRAG_PERSON_URL}
      token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
      grant-type: client_credentials
      scope: api://${BIDRAG_PERSON_SCOPE}/.default
      authentication:
        client-id: ${AZURE_APP_CLIENT_ID}
        client-secret: ${AZURE_APP_CLIENT_SECRET}
        client-auth-method: client_secret_basic

funksjonsbrytere:
  enabled: true
  unleash:
    uri: https://unleash.nais.io/api/
    cluster: ${NAIS_CLUSTER_NAME}
    applicationName: ${NAIS_APP_NAME}

overføre_hendelser:
  kjøreplan: ${OVERFØRE_HENDELSER_KJØREPLAN}
  lås:
      min: ${OVERFØRE_HENDELSER_LÅS_MIN}
      max: ${OVERFØRE_HENDELSER_LÅS_MAX}
publisere_personhendelser:
  kjøreplan: ${PUBLISERE_PERSONHENDELSER_KJØREPLAN}
  lås:
    min: ${PUBLISERE_PERSONHENDELSER_LÅS_MIN}
    max: ${PUBLISERE_PERSONHENDELSER_LÅS_MAX}
slette_hendelser:
  kjøreplan: ${SLETTE_HENDELSER_KJØREPLAN}
  lås:
    min: ${SLETTE_HENDELSER_LÅS_MIN}
    max: ${SLETTE_HENDELSER_LÅS_MAX}

management:
  endpoint.health.show-details: always
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/internal"
  health:
    db:
      enabled: true
  prometheus.metrics.export.enabled: true

egenskaper:
  generelt:
    antallMinutterForsinketVideresending: 120
    antallDagerLevetidForUtgaatteHendelser: ${DAGER_LEVETID_UTGÅTTE_HENDELSER}
  integrasjon:
    wmq:
      host: ${WMQ_HOST}
      port: ${WMQ_PORT}
      channel: ${WMQ_CHANNEL}
      queue-manager: ${WMQ_QUEUEMANAGER}
      username: srvbidrag-person-hen
      password: ${PASSORD_SRVBIDRAG_PERSON_HEN}
      timeout: ${WMQ_TIMEOUT}
      application-name: ${WMQ_APPLICATION_NAME}
      queueNameLivshendelser: ${WMQ_QUEUE_NAME_LIVSHENDELSER}
    bidrag-person:
        url: ${BIDRAG_PERSON_URL}
