# WMQ
WMQ_HOST: b27apvl222.preprod.local
WMQ_PORT: 1413
WMQ_CHANNEL: Q2_BID_PERS_HENDELSE
WMQ_QUEUEMANAGER: MQLS04
WMQ_TIMEOUT: 15000
WMQ_APPLICATION_NAME: bidrag-person-hendelse
WMQ_QUEUE_NAME_LIVSHENDELSER: QA.Q2_BISYS.PDL_LIVSHENDELSER

# Generelt
KJØREPLAN_OVERFØRE_HENDELSER: "0 0/5 * * * ?"