# WMQ
WMQ_HOST: a01apvl269.adeo.no
WMQ_PORT: 1414
WMQ_CHANNEL: P_BID_PERS_HENDELSE
WMQ_QUEUEMANAGER: MPLS02
WMQ_TIMEOUT: 15000
WMQ_APPLICATION_NAME: bidrag-person-hendelse
WMQ_QUEUE_NAME_LIVSHENDELSER: P.BISYS.PDL_LIVSHENDELSER