# WMQ
WMQ_HOST: mpls04.adeo.no
WMQ_PORT: 1414
WMQ_CHANNEL: P_BID_PERS_HENDELSE
WMQ_QUEUEMANAGER: MPLS04
WMQ_TIMEOUT: 15000
WMQ_APPLICATION_NAME: bidrag-person-hendelse
WMQ_QUEUE_NAME_LIVSHENDELSER: QA.P_BISYS.PDL_LIVSHENDELSER

# Generelt
OVERFØRE_HENDELSER_KJØREPLAN: "0 0/3 * * * ?"
OVERFØRE_HENDELSER_LÅS_MIN: PT2M
OVERFØRE_HENDELSER_LÅS_MAX: PT10M
SLETTE_HENDELSER_KJØREPLAN: "0 30 1 * * ?"
SLETTE_HENDELSER_LÅS_MIN: PT30S
SLETTE_HENDELSER_LÅS_MAX: PT1M
DAGER_LEVETID_UTGÅTTE_HENDELSER: 7
