# Generelt
OVERFØRE_HENDELSER_KJØREPLAN: "0 0/3 * * * ?"
OVERFØRE_HENDELSER_LÅS_MIN: PT2M
OVERFØRE_HENDELSER_LÅS_MAX: PT10M
PUBLISERE_PERSONHENDELSER_KJØREPLAN: "0 0/3 * * * ?"
PUBLISERE_PERSONHENDELSER_LÅS_MIN: PT2M
PUBLISERE_PERSONHENDELSER_LÅS_MAX: PT10M
SLETTE_HENDELSER_KJØREPLAN: "0 0 * * * ?"
SLETTE_HENDELSER_LÅS_MIN: PT30S
SLETTE_HENDELSER_LÅS_MAX: PT1M
DAGER_LEVETID_UTGÅTTE_HENDELSER: 7
ANTALL_MINUTTER_FORSINKET_VIDERESENDING: 0
ANTALL_TIMER_SIDEN_FORRIGE_PUBLISERING: -1
# Integrasjon
# WMQ
WMQ_HOST: b27apvl222.preprod.local
WMQ_PORT: 1413
WMQ_CHANNEL: Q2_BID_PERS_HENDELSE
WMQ_QUEUEMANAGER: MQLS04
WMQ_TIMEOUT: 15000
WMQ_APPLICATION_NAME: bidrag-person-hendelse
WMQ_QUEUE_NAME_LIVSHENDELSER: QA.Q2_BISYS.PDL_LIVSHENDELSER

# bidrag-person
BIDRAG_PERSON_URL: https://bidrag-person-q2.dev-fss-pub.nais.io/bidrag-person
BIDRAG_PERSON_SCOPE: dev-fss.bidrag.bidrag-person-q2
