# WMQ
WMQ_HOST: a01apvl269.adeo.no
WMQ_PORT: 1414
WMQ_CHANNEL: P_BIDRAG_PERSON_HENDELSE
WMQ_QUEUE_MANAGER: MPLS02
WMQ_TIMEOUT: 15000
WMQ_APPLICATION_NAME: bidrag-person-hendelse
WMQ_QUEUE_NAME_LIVSHENDELSER: P_BIDRAG_PERSON_HENDELSE.PDL_LIVSHENDELSE