spring:
  kafka:
    bootstrap-servers: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443
    properties:
      schema.registry.url: http://kafka-schema-registry.tpa:8081

# WMQ
WMQ_HOST: b27apvl222.preprod.local
WMQ_PORT: 1413
WMQ_CHANNEL: Q2_BID_PERS_HENDELSE
WMQ_QUEUE_MANAGER: MQLS04
WMQ_USERNAME: srvbdpers-hendelse
WMQ_PASSWORD: {MQ_PASSWORD}
WMQ_TIMEOUT: 15000
WMQ_APPLICATION_NAME: bidrag-person-hendelse