name: Deploy Bidrag kafka topics to dev
on:
  push:
    branches-ignore:
      - main
    paths:
      - '.nais/kafka/personhendelse.v1/topic_preprod.yml'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: deploy Bidrag personhendelse Kafka topic to dev
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/kafka/personhendelse.v1/topic_preprod.yml
          PRINT_PAYLOAD: true