name: Deploy kafka topics to prod
on:
  push:
    branches:
      - main
    paths:
      - '.nais/kafka/personhendelse.v1/topic_prod.yml'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: deploy Bidrag personhendelse Kafka topic to dev
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/kafka/personhendelse.v1/topic_prod.yml
          PRINT_PAYLOAD: true